# This is a basic workflow to help you get started with Actions

name: Ceedling with docker

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
    branches: [ main, action ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "unit-test"
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Build local Dockerfile
    #  run: docker build -t local < Dockerfile
    #- name: run tests
    #  run: docker run -it -v $PWD:/project local /project/do_test.sh
    - name: Ceedling tests
      uses: docker://throwtheswitch/madsciencelab:latest
      with:
        entrypoint: /github/workspace/do_test.sh
